src/wakawaka/models.py
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic


class WikiPage(models.Model):
    slug = models.CharField(_('slug'), max_length=255)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)

    content_type = models.ForeignKey(ContentType, null=True)
    object_id = models.PositiveIntegerField(null=True)
    group = generic.GenericForeignKey("content_type", "object_id")

    class Meta:
        verbose_name = _("Wiki page")
        verbose_name_plural = _("Wiki pages")
        ordering = ['slug']

    def __unicode__(self):
        return self.slug

    @property
    def current(self):
        return self.revisions.latest()

    @property
    def rev(self, rev_id):
        return self.revisions.get(pk=rev_id)

class Revision(models.Model):
    page = models.ForeignKey(WikiPage, related_name='revisions')
    content = models.TextField(_('content'))
    message = models.TextField(_('change message'), blank=True)
    creator = models.ForeignKey(User, blank=True, null=True, related_name='wakawaka_revisions')
    creator_ip = models.IPAddressField(_('creator ip'))
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)

    class Meta:
        verbose_name = _("Revision")
        verbose_name_plural = _("Revisions")
        ordering = ['-modified']
        get_latest_by = 'modified'

    def __unicode__(self):
        return ugettext('Revision %(created)s for %(page_slug)s') % {
            'created': self.created.strftime('%Y%m%d-%H%M'),
            'page_slug': self.page.slug,
        }

src/wakawaka/templates/wakawaka/base.html
{% load i18n %}

<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	{% block extrahead %}{% endblock %}
</head>
<body>
	{% if messages %}
	<ul class="messages">
	{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}

	{% spaceless %}
	<div class="info">
		<span>
			<a href="{% url wakawaka_index %}">{% trans "Start" %}</a>
		</span>
		<span>
			<a href="{% url wakawaka_revision_list %}">{% trans "Recent revisions" %}</a>
		</span>
		<span>
			<a href="{% url wakawaka_page_list %}">{% trans "All Pages" %}</a>
		</span>
	</div>
	{% endspaceless %}

	{% block content %}
	{% endblock %}
</body>
</html>

src/wakawaka/templates/wakawaka/changes.html
{% extends "wakawaka/base.html" %}

{% load wakawaka_tags %}
{% load i18n %}

{% block extrahead %}
	{{ block.super }}

	{# Don't let search engines scan this old revision #}
	{% if rev.is_not_current %}
		<meta name="robots" content="noindex" />
	{% endif %}
{% endblock %}

{% block title %}
	{% blocktrans with page.slug as slug %}Changes for {{ slug  }}{% endblocktrans %}
{% endblock %}

{% block content %}
	<h1>{{ page.slug }}</h1>

	<pre class="changes">{{ diff }}</pre>
	{% include "wakawaka/revision_table.html" %}
{% endblock %}

src/wakawaka/templates/wakawaka/edit.html
{% extends "wakawaka/base.html" %}

{% load i18n %}

{% block title %}
    {% if page.is_initial %}
        {% blocktrans with page.slug as slug %}Add {{ slug  }}{% endblocktrans %}
    {% else %}
        {% blocktrans with page.slug as slug %}Edit {{ slug  }}{% endblocktrans %}
    {% endif %}
{% endblock %}

{% block content %}
	<h1>
	    {% if page.is_initial %}
	        {% blocktrans with page.slug as slug %}Add {{ slug  }}{% endblocktrans %}
	    {% else %}
	        {% blocktrans with page.slug as slug %}Edit {{ slug  }}{% endblocktrans %}
	    {% endif %}
	</h1>

	{% if rev.is_not_current %}
	<p class="revert-warning">{% trans "You are editing an revision which is not the latest!" %}</p>
	{% endif %}

	<form class="wakawaka_edit_form" method="POST" action="">
		{{ form.as_p }}
		{% csrf_token %}
		<p>
            <input type="submit" value="{% trans "Save changes" %}" />
            {% trans "or" %} <a href="
			{% if page.is_initial %}
				javascript:window.history.go(-1);
			{% else %}
				{% url wakawaka_page slug=page.slug %}
			{% endif %}
			">{% trans "Cancel" %}</a>
		</p>
	</form>

	{% if not page.is_initial and delete_form %}
	<form class="wakawaka_delete_form" method="POST" action="" onsubmit="return confirm('{% trans "Please confirm deletion" %}');">
		{{ delete_form.as_p }}
		<p>
			<input type="submit" value="{% trans "Delete" %}" />
		</p>
	</form>
	{% endif %}

	<h2>{% trans "Revisions for this page" %}</h2>

	{% include "wakawaka/revision_table.html" %}
{% endblock %}

src/wakawaka/templates/wakawaka/page.html
{% extends "wakawaka/base.html" %}

{% load wakawaka_tags %}
{% load i18n %}

{% block extrahead %}
	{{ block.super }}

	{# Don't let search engines scan this old revision #}
	{% if rev.is_not_current %}
		<meta name="robots" content="noindex" />
	{% endif %}
{% endblock %}

{% block title %}
	{{ page.slug }}
{% endblock %}

{% block content %}
	<h1><a href="{% url wakawaka_page slug=page.slug %}">{{ page.slug }}</a></h1>

	{% if rev.is_not_current %}
	<p class="revert-warning">
		{% trans "You are viewing an older revision!" %}
		<a href="{% url wakawaka_page slug=page.slug %}">
		  {% trans "See the latest version" %}
		</a>
	</p>
	{% endif %}

	<div class="page">
	{{ rev.content|urlize|wikify|linebreaks }}
	</div>

	{% spaceless %}
	<div class="info">
    	<span>
    		<strong>{{ page.slug }}</strong>
    	</span>
    	<span>
    		{% blocktrans with page.current.creator as creator and rev.modified|date:_("DATETIME_FORMAT") as modified %}
    		    Recently modified by <em>{{ creator }}</em>: {{ modified }}
    		{% endblocktrans %}
    		(<a href="{% url wakawaka_revision_list slug=page.slug %}">{% trans "History" %}</a>)
    	</span>
    	
    	{% if perms.wakawaka.change_wikipage %}
    	<span>
    		<a href="{% url wakawaka_edit slug=page.slug %}">{% trans "Edit" %}</a>
    	</span>
    	{% endif %}
	</div>
	{% endspaceless %}
{% endblock %}

src/wakawaka/templates/wakawaka/page_list.html
{% extends "wakawaka/base.html" %}

{% load i18n %}

{% block title %}
	{% trans "All wiki pages" %}
{% endblock %}

{% block content %}
	<h1>{% trans "All wiki pages" %}</h1>
	<ul>
	{% for page in page_list %}
	<li><a href="{% url wakawaka_page slug=page.slug %}">{{ page.slug }}</a>
	{% endfor %}
	</ul>
{% endblock %}

src/wakawaka/templates/wakawaka/revision_list.html
{% extends "wakawaka/base.html" %}

{% load i18n %}

{% block title %}
	{% trans "List of all revisions" %}
{% endblock %}

{% block content %}
	<h1>{% trans "List of all revisions" %}</h1>

	<table class="history" border="1">
	<tr>
        <th>{% trans "Page" %}</th>
        <th>{% trans "Changed" %}</th>
        <th>{% trans "Message" %}</th>
        <th>{% trans "Modified by" %}</th>
		<th>&nbsp;</th>
	</tr>
	{% for rev in revision_list %}
	<tr>
		<td>{{ rev.page.slug }}</td>
		<td class="modifed">{{ rev.modified|timesince }} ago</td>
		<td class="message">{{ rev.message }}</td>
		<td class="creator">{{ rev.creator.username }}</td>
		<td class="options">
			<a href="{% url wakawaka_page slug=rev.page.slug, rev_id=rev.pk %}">{% trans "View" %}</a>
			{% if user.is_authenticated %}
			<a href="{% url wakawaka_edit slug=rev.page.slug, rev_id=rev.pk %}">{% trans "Revert" %}</a>
			{% endif %}
		</td>
	</tr>
	{% endfor %}
	</table>

{% endblock %}

src/wakawaka/templates/wakawaka/revision_table.html
{% load i18n %}

<form method="GET" action="{% url wakawaka_changes slug=page.slug %}">
<table class="history" border="1">
<tr>
	<th>{% trans "Compare" %}</th>
	<th>{% trans "Changed" %}</th>
	<th>{% trans "Message" %}</th>
	<th>{% trans "Modified by" %}</th>
	<th>&nbsp;</th>
</tr>
{% for rev in page.revisions.all %}
<tr>
	<td class="compare">
		<input type="radio" name="a" value="{{ rev.pk }}"
			{% if rev_a %}
				{% ifequal rev_a.pk rev.pk %}checked{% endifequal %}
			{% else %}
				{% ifequal forloop.counter 1 %}checked{% endifequal %}
			{% endif %}
		/>
		<input type="radio" name="b" value="{{ rev.pk }}"
			{% if rev_b %}
				{% ifequal rev_b.pk rev.pk %}checked{% endifequal %}
			{% else %}
				{% ifequal page.revisions.all|length 1 %}
					checked
				{% else %}
					{% ifequal forloop.counter 2 %}checked{% endifequal %}
				{% endifequal %}
			{% endif %}
		/>
	</td>
	<td class="modifed">{{ rev.modified|timesince }} ago</td>
	<td class="message">{{ rev.message }}</td>
	<td class="creator">{{ rev.creator.username }}</td>
	<td class="options">
		<a href="{% url wakawaka_page slug=page.slug, rev_id=rev.pk %}">{% trans "View" %}</a>
		<a href="{% url wakawaka_edit slug=page.slug, rev_id=rev.pk %}">{% trans "Revert" %}</a>
	</td>
</tr>
{% endfor %}
</table>

<p><input type="submit" value="{% trans "Compare revisions" %}"/></p>
</form>

src/wakawaka/templates/wakawaka/revisions.html
{% extends "wakawaka/base.html" %}

{% load i18n %}

{% block title %}
    {% blocktrans with page.slug as slug %}History for {{ slug }}{% endblocktrans %}
{% endblock %}

{% block content %}
	<h1>{% blocktrans with page.slug as slug %}History for {{ slug }}{% endblocktrans %}</h1>

	{% include "wakawaka/revision_table.html" %}
{% endblock %}